"""Application-level constants for PLOS AI."""

from __future__ import annotations

# ---- Application identity ----
APP_NAME = "PLOS AI"
APP_NAME_SAFE = "plos_ai"
VERSION = "2.3.1"

# ---- Default Ollama settings ----
DEFAULT_OLLAMA_HOST = "http://127.0.0.1:11434"
DEFAULT_OLLAMA_TIMEOUT = 300

# ---- Default model names ----
DEFAULT_TEXT_MODEL = "qwen2.5:7b-q4_K_M"
DEFAULT_VISION_MODEL = "qwen2.5-vl:7b-q4_K_M"
DEFAULT_EMBEDDING_MODEL = "nomic-embed-text"

# ---- Focus timer (pomodoro) & daily goal ----
POMODORO_FOCUS_MINUTES = 25
POMODORO_BREAK_MINUTES = 5
DEFAULT_DAILY_GOAL_MINUTES = 30

# ---- OCR defaults ----
DEFAULT_OCR_ENGINE = "vl"
DEFAULT_OCR_LANGUAGE = "ch"
DEFAULT_OCR_CONFIDENCE_THRESHOLD = 0.7
DEFAULT_OCR_USE_VL_CORRECTION = True

# ---- Image preprocessing ----
MAX_IMAGE_DIMENSION = 2048

# ---- RAG defaults ----
DEFAULT_CHUNK_SIZE = 500
DEFAULT_CHUNK_OVERLAP = 50
DEFAULT_RAG_TOP_K = 4
DEFAULT_EMBEDDING_DIMENSION = 768

# ---- SM-2 spaced repetition defaults ----
SM2_INITIAL_EASE = 2.5
SM2_MIN_EASE = 1.3
SM2_FIRST_INTERVAL = 1
SM2_SECOND_INTERVAL = 6

# ---- UI defaults ----
DEFAULT_THEME = "light"
DEFAULT_WINDOW_WIDTH = 1280
DEFAULT_WINDOW_HEIGHT = 800
DEFAULT_UI_LANGUAGE = "zh_CN"

# ---- Logging defaults ----
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_MAX_FILE_SIZE_MB = 10
DEFAULT_LOG_BACKUP_COUNT = 5

# ---- Hotkey defaults ----
DEFAULT_HOTKEY_SCREENSHOT = "ctrl+alt+a"
DEFAULT_HOTKEY_CLIPBOARD_CAPTURE = "ctrl+alt+v"
DEFAULT_HOTKEY_SHOW_WINDOW = "ctrl+alt+s"

# ---- File / path defaults ----
DEFAULT_DATA_DIR_NAME = "data"
DEFAULT_IMAGES_DIR_NAME = "images"
DEFAULT_ATTACHMENTS_DIR_NAME = "attachments"
DEFAULT_LOGS_DIR_NAME = "logs"
DEFAULT_CONFIG_DIR_NAME = "config"
DEFAULT_CONFIG_FILE_NAME = "config.toml"
DEFAULT_DB_FILE_NAME = "plos.db"
DEFAULT_CHROMA_DIR_NAME = "chroma"

__all__ = [
    "APP_NAME",
    "APP_NAME_SAFE",
    "DEFAULT_ATTACHMENTS_DIR_NAME",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CONFIG_DIR_NAME",
    "DEFAULT_CONFIG_FILE_NAME",
    "DEFAULT_DATA_DIR_NAME",
    "DEFAULT_DB_FILE_NAME",
    "DEFAULT_EMBEDDING_DIMENSION",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_HOTKEY_CLIPBOARD_CAPTURE",
    "DEFAULT_HOTKEY_SCREENSHOT",
    "DEFAULT_HOTKEY_SHOW_WINDOW",
    "DEFAULT_IMAGES_DIR_NAME",
    "DEFAULT_LOG_BACKUP_COUNT",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_LOG_MAX_FILE_SIZE_MB",
    "DEFAULT_LOGS_DIR_NAME",
    "DEFAULT_DAILY_GOAL_MINUTES",
    "DEFAULT_OCR_CONFIDENCE_THRESHOLD",
    "POMODORO_BREAK_MINUTES",
    "POMODORO_FOCUS_MINUTES",
    "DEFAULT_OCR_ENGINE",
    "DEFAULT_OCR_LANGUAGE",
    "DEFAULT_OCR_USE_VL_CORRECTION",
    "DEFAULT_OLLAMA_HOST",
    "DEFAULT_OLLAMA_TIMEOUT",
    "DEFAULT_RAG_TOP_K",
    "DEFAULT_TEXT_MODEL",
    "DEFAULT_THEME",
    "DEFAULT_UI_LANGUAGE",
    "DEFAULT_VISION_MODEL",
    "DEFAULT_WINDOW_HEIGHT",
    "DEFAULT_WINDOW_WIDTH",
    "MAX_IMAGE_DIMENSION",
    "SM2_FIRST_INTERVAL",
    "SM2_INITIAL_EASE",
    "SM2_MIN_EASE",
    "SM2_SECOND_INTERVAL",
    "VERSION",
]
